#! /bin/sh
### BEGIN INIT INFO
# Provides:          jackd
# Required-Start:    $local_fs alsa-utils
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts jackd
# Description:       Starts jackd daemon process needed
#                    to listen to smoke alarms 
### END INIT INFO

# Process name
PROCNAME=jackd
PROCRUNDIR=/usr/local/bin/
SERVICENAME=jackd
PIDDIR=/var/run/leeo/
PIDFILE=$PIDDIR$SERVICENAME.pid
DAEMON=$PROCRUNDIR$PROCNAME
OPTIONS="-p 8 -d alsa -r 8000 -p 100"

if [ ! -d "$PIDDIR" ]; then
  mkdir $PIDDIR
fi

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting $SERVICENAME"
    echo $DAEMON $OPTIONS
    sleep 10
    amixer cset name="PGA Capture Volume" 80%,80%
    /sbin/start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --name jackd --startas $DAEMON -- $OPTIONS
    echo "$SERVICENAME started"
    ;;
  stop)
    echo -n "Stopping $SERVICENAME"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    STATUS=$(/sbin/start-stop-daemon --status --pidfile $PIDFILE --name jackd > /dev/null)$?
    if [ $STATUS -eq 0 ]; then
      echo "$SERVICENAME is running"
    else
      echo "$SERVICENAME is not running"
    fi 
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICENAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

