#! /bin/sh
### BEGIN INIT INFO
# Provides:          jack-leeo-client
# Required-Start:    jackd emergency-notification-handler
# Required-Stop:     jackd emergency-notification-handler
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts jack-leeo-client
# Description:       Starts jack-leeo-client daemon process to 
#	             send a trap indicating that a smoke alarm 
#                    sound was captured 
### END INIT INFO

# Process name
PROCNAME=jack-leeo-client
PROCRUNDIR=/usr/bin/
SERVICENAME=jack-leeo-client
PIDDIR=/var/run/leeo/
PIDFILE=$PIDDIR$SERVICENAME.pid
DAEMON=$PROCRUNDIR$PROCNAME
export LD_LIBRARY_PATH=/usr/local/lib

if [ ! -d "$PIDDIR" ]; then
  mkdir $PIDDIR
fi

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting $SERVICENAME"
    echo $DAEMON
    sleep 5
    /sbin/start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --name jack-leeo-clien --startas $DAEMON
    echo "$SERVICENAME started"
    ;;
  stop)
    echo -n "Stopping $SERVICENAME"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    STATUS=$(/sbin/start-stop-daemon --status --pidfile $PIDFILE --name jack-leeo-clien > /dev/null)$?
    if [ $STATUS -eq 0 ]; then
      echo "$SERVICENAME is running"
    else
      echo "$SERVICENAME is not running"
    fi 
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICENAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

