#! /bin/sh
### BEGIN INIT INFO
# Provides:          leeo-service
# Required-Start:    $remote_fs $networking $time
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts leeo-service
# Description:       Starts leeo_service daemon process to stream 
#                    device data to webserver
### END INIT INFO

# Process name
PROCNAME=leeo_forever.js
MONITORNAME=leeo-monitor
PROCRUNDIR=/usr/lib/leeonl/customer_image/leeo_services/
SERVICENAME=leeo-service
PIDDIR=/var/run/leeo/
MONITORPIDFILE=$PIDDIR$MONITORNAME.pid
PIDFILE=$PIDDIR$SERVICENAME.pid
DAEMON=$PROCRUNDIR$PROCNAME
NEWDAEMON="/usr/local/bin/node "$DAEMON
echo $NEWDAEMON

if [ ! -d "$PIDDIR" ]; then
  mkdir $PIDDIR
fi

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting $SERVICENAME"
    echo $DAEMON
    export PATH=$PATH:/usr/local/sbin
    sleep 1
    /sbin/start-stop-daemon --start --verbose --background --make-pidfile --pidfile $PIDFILE --name leeo-service --startas $NEWDAEMON
    echo "$SERVICENAME started"
    ;;
  stop)
    echo -n "Stopping $SERVICENAME"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE
    /sbin/start-stop-daemon --stop --pidfile $MONITORPIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    STATUS=$(/sbin/start-stop-daemon --status --pidfile $PIDFILE --name leeo-service > /dev/null)$?
    if [ $STATUS -eq 0 ]; then
      echo "$SERVICENAME is running"
    else
      echo "$SERVICENAME is not running"
    fi 
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICENAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
